---


#- name: Creating directory for DOCKER API
#  file:
#    path: "{{ docker_config_directory }}"
#    state: directory
#    mode: 0755

- name: Exposing DOCKER API port
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_config_directory }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - docker-external.conf

- name: Start Docker
  service:
    name: docker
    state: started